### ISSUE TITLE
jsoncpp version

### ISSUE THREAD

**Issue by benman1** [captain-igloo/greentop#1]
Hi
 This seems like a very useful library. Thanks for working on this. In compiling, I am running into a problem with the deprecated FastWriter in jsoncpp. I tried to fix them in greentop (see patch.txt), but it seems to be stacking up. They all look like this:
 
Undefined symbols for architecture x86_64:
  "Json::ValueIteratorBase::increment()", referenced from:
      Json::ValueConstIterator::operator++() in StatementItem.o
      Json::ValueConstIterator::operator++() in Runner.o
      Json::ValueConstIterator::operator++() in RunnerCatalog.o
...

 I've also appended the original error without any changes, and another patch to include macos as a platform. 

 So my questions: how to make this work? Which version of jsoncpp are you compiling against? (optional question:) How to fix it to make it work with the current version of jsoncpp? 

Thanks!
Ben.

[error.txt](https://github.com/captain-igloo/greentop/files/1616013/error.txt)
[patchMac.txt](https://github.com/captain-igloo/greentop/files/1616030/patchMac.txt)
[patch.txt](https://github.com/captain-igloo/greentop/files/1616007/patch.txt)

**Comment by benman1** [comment]
I found it. The g++ flags for curl and jsoncpp were missing.

**Comment by captain-igloo** [comment]
You shouldn't need to link curl or jsoncpp since you are building a shared library.  Rather you would link those two + greentop when building an app that uses greentop.  I think the problem is a difference between gcc on linux and OSX; OSX uses "-dynamiclib" and linux uses "-shared".

So you could try changing -shared to -dynamiclib in your Makefile.

**Comment by benman1** [comment]
Thanks for getting back to me, much appreciated. I changed it but still got the same errors (Apple LLVM version 9.0.0). It only goes through if I list the libraries, and I haven't looked up how to have it not throw these errors. I am a bit rusty with c++ and linking, to be honest.

**Comment by benman1** [comment]
These flags work on macos: `-Wl,-undefined -Wl,dynamic_lookup`

You can add `-shared` in order to make it work on linux/cygwin as well.

**Comment by captain-igloo** [comment]
So what's the whole command that you use?  And have you tried linking greentop into your app and using it ?

**Comment by benman1** [comment]
For a c++ example program it works fine. 
```bash
g++ getAccountStatement.cpp -I. -std=c++11 lib/libgreentop.so -ljsoncpp
./a 
Usage: ./a.out <application-key> <username> <password>
```
I am working with cython and still struggling through Segmentation Faults, "pythreadstate_get no current thread", and lot of other things. 

I'll append a Makefile for greentop. You'll see that I only made minor changes.
[Makefile.txt](https://github.com/captain-igloo/greentop/files/1620244/Makefile.txt)

**Comment by captain-igloo** [comment]
I've added -Wl,-undefined -Wl,dynamic_lookup and fixed the strptime() thing as well.  So it should now compile fine on OSX, let me know if it doesn't.
